// Export all DTOs
export * from "./auth.dto";
export * from "./user.dto";
export * from "./seat.dto";
export * from "./notification.dto";
export * from "./stats.dto";
export * from "./school-api.dto";
export * from "./scheduler.dto";
export * from "./room.dto";
export * from "./dashboard.dto";
