// ==================== 공개 설정 타입 ====================
export type StudyVisibility = "PUBLIC" | "PASSWORD" | "PRIVATE";
export type StudyMemberRole = "OWNER" | "ADMIN" | "MEMBER";
export type JoinRequestStatus = "PENDING" | "APPROVED" | "REJECTED";
export type AttendanceStatus =
	| "PRESENT"
	| "LATE"
	| "EARLY_LEAVE"
	| "ABSENT"
	| "VACATION";
export type VacationStatus = "PENDING" | "APPROVED" | "REJECTED";

// ==================== 스터디 그룹 ====================

// 스터디 생성 요청
export interface CreateStudyGroupDto {
	name: string;
	description?: string;
	visibility: StudyVisibility;
	password?: string; // visibility가 PASSWORD일 때 필수
	tags?: string[];
	maxMembers?: number;
	checkInStartTime: string; // "08:00"
	checkInEndTime: string; // "10:00"
	checkOutMinTime: string; // "18:00"
	minUsageMinutes: number; // 최소 이용 시간 (분)
	operatingDays: number[]; // [1,2,3,4,5] (월~금)
	displayName?: string; // 스터디 내 닉네임 (없으면 실명 사용)
}

// 스터디 수정 요청
export interface UpdateStudyGroupDto {
	name?: string;
	description?: string;
	visibility?: StudyVisibility;
	password?: string;
	tags?: string[];
	maxMembers?: number;
	checkInStartTime?: string;
	checkInEndTime?: string;
	checkOutMinTime?: string;
	minUsageMinutes?: number;
	operatingDays?: number[];
	thumbnailUrl?: string;
}

// 스터디 목록 아이템 (Public)
export interface StudyGroupListItem {
	groupId: string;
	name: string;
	description?: string;
	visibility: StudyVisibility;
	tags?: string[];
	maxMembers?: number;
	memberCount: number;
	checkInStartTime: string;
	checkInEndTime: string;
	checkOutMinTime: string;
	thumbnailUrl?: string;
	createdAt: string;
	// 오늘의 출석률 (옵션)
	todayAttendanceRate?: number;
}

// 스터디 상세 정보 (Public)
export interface StudyGroupDetail {
	groupId: string;
	name: string;
	description?: string;
	visibility: StudyVisibility;
	tags?: string[];
	maxMembers?: number;
	memberCount: number;
	checkInStartTime: string;
	checkInEndTime: string;
	checkOutMinTime: string;
	minUsageMinutes: number;
	operatingDays: number[];
	thumbnailUrl?: string;
	createdAt: string;
	updatedAt: string;
	// 멤버 목록 (닉네임만)
	members: StudyMemberPublic[];
}

// ==================== 스터디 멤버 ====================

// 공개용 멤버 정보
export interface StudyMemberPublic {
	memberId: string;
	displayName: string;
	role: StudyMemberRole;
	joinedAt: string;
}

// 상세 멤버 정보 (관리자용)
export interface StudyMemberDetail {
	memberId: string;
	studentId: string;
	displayName: string;
	role: StudyMemberRole;
	joinedAt: string;
	lastActiveAt?: string;
	// 출석 통계
	attendanceStats?: {
		totalDays: number;
		presentDays: number;
		lateDays: number;
		absentDays: number;
		attendanceRate: number;
	};
}

// 멤버 역할 변경 요청
export interface UpdateMemberRoleDto {
	role: StudyMemberRole;
}

// ==================== 가입 관련 ====================

// 참가 신청 요청
export interface JoinStudyRequestDto {
	displayName: string; // 스터디 내에서 사용할 닉네임 (신청자가 입력)
	message?: string;
}

// 비밀번호로 가입 요청
export interface JoinStudyWithPasswordDto {
	password: string;
	displayName: string;
}

// 초대 코드로 가입 요청
export interface JoinStudyWithCodeDto {
	inviteCode: string;
	displayName: string;
}

// 참가 신청 정보
export interface JoinRequestInfo {
	requestId: string;
	studentId: string;
	studentName: string;
	displayName: string; // 신청자가 요청한 스터디 내 닉네임
	message?: string;
	status: JoinRequestStatus;
	createdAt: string;
	processedAt?: string;
	rejectionReason?: string;
}

// 참가 신청 처리 요청
export interface ProcessJoinRequestDto {
	status: "APPROVED" | "REJECTED";
	rejectionReason?: string;
	displayName?: string; // 승인 시 닉네임
}

// ==================== 출퇴근 관련 ====================

// 오늘의 출퇴근 현황 (Public)
export interface TodayAttendancePublic {
	memberId: string;
	displayName: string;
	status: AttendanceStatus | "NOT_YET"; // 아직 출근 안함
	checkInTime?: string;
	checkOutTime?: string;
	usageMinutes?: number;
	isCurrentlyIn?: boolean; // 현재 도서관에 있는지
}

// 출퇴근 기록 상세
export interface AttendanceRecordDetail {
	recordId: string;
	date: string;
	checkInTime?: string;
	checkOutTime?: string;
	status: AttendanceStatus;
	usageMinutes: number;
	note?: string;
	isAutoGenerated: boolean;
}

// 주간/월간 출석 통계
export interface AttendanceStats {
	totalOperatingDays: number;
	presentDays: number;
	lateDays: number;
	earlyLeaveDays: number;
	absentDays: number;
	vacationDays: number;
	attendanceRate: number; // 출석률 (%)
	totalUsageMinutes: number;
	averageUsageMinutes: number;
}

// ==================== 휴가 관련 ====================

// 휴가 신청 요청
export interface CreateVacationRequestDto {
	startDate: string; // "YYYY-MM-DD"
	endDate: string;
	reason?: string;
}

// 휴가 정보
export interface VacationRequestInfo {
	requestId: string;
	studentId: string;
	displayName: string;
	startDate: string;
	endDate: string;
	reason?: string;
	status: VacationStatus;
	createdAt: string;
	processedAt?: string;
}

// ==================== 응답 타입 ====================

export interface StudyActionResponse {
	success: boolean;
	message: string;
	data?: any;
}

// 스터디 목록 응답 (페이지네이션)
export interface StudyGroupListResponse {
	items: StudyGroupListItem[];
	pagination: {
		page: number;
		limit: number;
		total: number;
		totalPages: number;
	};
}

// 내 스터디 목록 응답
export interface MyStudyGroupItem extends StudyGroupListItem {
	myRole: StudyMemberRole;
	myDisplayName: string;
	// 내 출석 통계
	myAttendanceStats?: AttendanceStats;
}

export interface MyStudyGroupListResponse {
	items: MyStudyGroupItem[];
}
