import {
	Entity,
	PrimaryGeneratedColumn,
	Column,
	CreateDateColumn,
	UpdateDateColumn,
	ManyToOne,
	JoinColumn,
	Relation,
	Index,
	Unique,
} from "typeorm";

export type AttendanceStatus =
	| "PRESENT" // 정상 출근
	| "LATE" // 지각
	| "EARLY_LEAVE" // 조퇴
	| "ABSENT" // 결석
	| "VACATION"; // 휴가

@Entity()
@Unique("uq_attendance_record", ["groupId", "studentId", "date"])
@Index("idx_attendance_group_date", ["groupId", "date"])
@Index("idx_attendance_student", ["studentId"])
export class AttendanceRecord {
	@PrimaryGeneratedColumn("uuid")
	recordId!: string;

	@Column()
	groupId!: string;

	@Column()
	studentId!: string;

	// 날짜 (YYYY-MM-DD)
	@Column({ type: "date" })
	date!: Date;

	// 출퇴근 시간 (도서관 기록 기반)
	@Column({ length: 5, nullable: true })
	checkInTime?: string; // "08:32"

	@Column({ length: 5, nullable: true })
	checkOutTime?: string; // "18:45"

	// 상태
	@Column({ type: "varchar", length: 20 })
	status!: AttendanceStatus;

	// 실제 이용 시간 (분)
	@Column({ type: "int", default: 0 })
	usageMinutes!: number;

	// 비고
	@Column({ type: "text", nullable: true })
	note?: string;

	// 자동 생성 여부 (도서관 기록 기반 자동 생성 vs 수동 입력)
	@Column({ type: "boolean", default: true })
	isAutoGenerated!: boolean;

	// 관계
	@ManyToOne("StudyGroup", "attendanceRecords", { onDelete: "CASCADE" })
	@JoinColumn({ name: "groupId" })
	studyGroup!: Relation<any>;

	@ManyToOne("User")
	@JoinColumn({ name: "studentId" })
	user!: Relation<any>;

	@CreateDateColumn()
	createdAt!: Date;

	@UpdateDateColumn()
	updatedAt!: Date;
}
